LANGS = {
    "en": {
        # General UI
        "name_prompt": "What is your slime's name?",
        "slime_status": "Slime Status",
        "feed": "Feed",
        "play": "Play",
        "rest": "Rest",
        "status": "Status",
        "shop": "Shop",
        "catch": "Catch",
        "clean": "Clean",
        "save": "Save",
        "load": "Load",
        "inventory": "Inventory",

        # Tooltips
        "feed_tip": "Feed your slime to reduce hunger.",
        "play_tip": "Play to increase happiness.",
        "rest_tip": "Let your slime rest to restore energy.",
        "status_tip": "Refresh the status display.",
        "shop_tip": "Buy upgrades, backgrounds, and button colors.",
        "catch_tip": "Play the treat-catching minigame.",
        "clean_tip": "Clean your slime by removing dirt spots.",
        "save_tip": "Save your slime's progress.",
        "load_tip": "Load your last saved game.",
        "inventory_tip": "View and equip your items.",

        # Status/Shop/Minigame
        "coins": "Coins",
        "happiness": "Happiness",
        "energy": "Energy",
        "worn_items": "Worn items",
        "upgrades": "Upgrades",
        "none": "None",
        "shop_title": "Slime Shop",
        "already_own": "You already own",
        "not_enough_coins": "Not enough coins for this upgrade.",
        "bought": "You bought",
        "game_saved": "Game saved successfully!",
        "game_loaded": "Game loaded successfully!",
        "no_save": "No saved game found.",

        # Minigame
        "game_over": "Game Over!",
        "caught": "Caught",
        "bonus": "Bonus",
        "cleaned": "Cleaned!",
        "clean_done": "All clean!",

        # Item names (for shop, inventory, status)
        "item_names": {
            "Crown": "Crown",
            "Hat": "Hat",
            "Bow": "Bow",
            "Glasses": "Glasses",
            "Bed": "Bed",
            "Toy": "Toy",
            "Lamp": "Lamp",
            "Poster": "Poster",
            "Pink Background": "Pink Background",
            "Blue Background": "Blue Background",
            "Mint Background": "Mint Background",
            "Yellow Background": "Yellow Background",
            "Purple Background": "Purple Background",
            "Gray Background": "Gray Background",
            "Green Buttons": "Green Buttons",
            "Pink Buttons": "Pink Buttons",
            "Blue Buttons": "Blue Buttons",
            "Yellow Buttons": "Yellow Buttons",
            "Purple Buttons": "Purple Buttons",
            "Gray Buttons": "Gray Buttons",
            "Rename Slime": "Rename Slime",
            # Add more as needed
        },

        # Inventory
        "inventory_equip": "Equip",
        "inventory_unequip": "Unequip",
        "Head": "Head",
        "Face": "Face",
        "Body": "Body",
        "Room": "Room",
        "Background": "Background",
        "Buttons": "Buttons",
    },

    "sk": {
        # General UI
        "name_prompt": "Ako sa volá tvoj slizák?",
        "slime_status": "Stav slizáka",
        "feed": "Nakŕmiť",
        "play": "Hrať sa",
        "rest": "Oddychovať",
        "status": "Stav",
        "shop": "Obchod",
        "catch": "Chytiť",
        "clean": "Upratať",
        "save": "Uložiť",
        "load": "Načítať",
        "inventory": "Inventár",

        # Tooltips
        "feed_tip": "Nakŕm svojho slizáka, aby nebol hladný.",
        "play_tip": "Hraj sa, aby bol šťastný.",
        "rest_tip": "Dopraj slizákovi oddych na energiu.",
        "status_tip": "Obnov zobrazenie stavu.",
        "shop_tip": "Kúp vylepšenia, pozadia a farby tlačidiel.",
        "catch_tip": "Hraj minihru s chytaním maškŕt.",
        "clean_tip": "Upratať špinu zo slizáka.",
        "save_tip": "Ulož pokrok slizáka.",
        "load_tip": "Načítaj poslednú uloženú hru.",
        "inventory_tip": "Zobraziť a nasadiť predmety.",

        # Status/Shop/Minigame
        "coins": "Mince",
        "happiness": "Šťastie",
        "energy": "Energia",
        "worn_items": "Nosené predmety",
        "upgrades": "Vylepšenia",
        "none": "Žiadne",
        "shop_title": "Obchod so slizákom",
        "already_own": "Už vlastníš",
        "not_enough_coins": "Nedostatok mincí na toto vylepšenie.",
        "bought": "Kúpil si",
        "game_saved": "Hra bola úspešne uložená!",
        "game_loaded": "Hra bola úspešne načítaná!",
        "no_save": "Nebola nájdená žiadna uložená hra.",

        # Minigame
        "game_over": "Koniec hry!",
        "caught": "Chytené",
        "bonus": "Bonus",
        "cleaned": "Upratané!",
        "clean_done": "Všetko čisté!",

        # Item names (for shop, inventory, status)
        "item_names": {
            "Crown": "Koruna",
            "Hat": "Klobúk",
            "Bow": "Mašľa",
            "Glasses": "Okuliare",
            "Bed": "Posteľ",
            "Toy": "Hračka",
            "Lamp": "Lampa",
            "Poster": "Plagát",
            "Pink Background": "Ružové pozadie",
            "Blue Background": "Modré pozadie",
            "Mint Background": "Mätové pozadie",
            "Yellow Background": "Žlté pozadie",
            "Purple Background": "Fialové pozadie",
            "Gray Background": "Sivé pozadie",
            "Green Buttons": "Zelené tlačidlá",
            "Pink Buttons": "Ružové tlačidlá",
            "Blue Buttons": "Modré tlačidlá",
            "Yellow Buttons": "Žlté tlačidlá",
            "Purple Buttons": "Fialové tlačidlá",
            "Gray Buttons": "Sivé tlačidlá",
            "Rename Slime": "Premenovať slizáka",
            # Add more as needed
        },

        # Inventory
        "inventory_equip": "Nasadiť",
        "inventory_unequip": "Zložiť",
        "Head": "Hlava",
        "Face": "Tvár",
        "Body": "Telo",
        "Room": "Izba",
        "Background": "Pozadie",
        "Buttons": "Tlačidlá",
    }
}